# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: user42 <user42@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/02/05 17:55:50 by user42            #+#    #+#              #
#    Updated: 2021/02/18 13:53:31 by user42           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FROM	alpine:latest

RUN		apk update && apk add --no-cache influxdb

COPY	./run.sh .
RUN		chmod +x ./run.sh

EXPOSE 8086

CMD ./run.sh