apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector: 
    app: grafana
  type: LoadBalancer  
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: my-grafana
        imagePullPolicy: Never
        env:
        - name: AUTH_USER
          valueFrom:
            secretKeyRef:
              name: influxdb-secrets
              key: INFLUXDB_USERNAME
        - name: AUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: influxdb-secrets
              key: INFLUXDB_PASSWORD
        ports:
        - name: grafana
          containerPort: 3000