apiVersion: v1
kind: Secret
metadata:
  name: influxdb-secrets
type: Opaque
stringData:
  INFLUXDB_DATABASE: influxdb
  INFLUXDB_USERNAME: root
  INFLUXDB_PASSWORD: root1234
  INFLUXDB_HOST: influxdb
  INFLUXDB_URL: http://influxdb-service:8086