# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: user42 <user42@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/02/10 18:09:59 by user42            #+#    #+#              #
#    Updated: 2021/02/15 12:22:08 by user42           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FROM	alpine:latest

RUN		apk update && apk add --no-cache telegraf

RUN		mkdir -p /etc/telegraf
COPY	./telegraf.conf /etc/telegraf

COPY	./run.sh .
RUN		chmod +x ./run.sh

EXPOSE	8125

CMD ./run.sh